### ISSUE TITLE
Should there be a space after `p.` and `pp.`?

### ISSUE THREAD

**Issue by alexreg** [alex-ball/bathbib#12]
In most biblatex styles, there is a space after `p.` and `pp.` when you cite page numbers, e.g., `\autocite[3]{foo}` and `\autocite[10--20]{bar}`. Is it clearly specified by the Bath style guide that there shouldn't be? I can't find out, unfortunately.

**Comment by alex-ball** [comment]
In most referencing styles, there certainly is and should be a space. One of the peculiarities of Bath's Harvard style, however, is that abbreviation dots are not separated by a space from a following digit or initial. The Burchard (1965) and Reid (1967) examples in the manual are verbatim from the [Library's guidance page](https://library.bath.ac.uk/referencing/harvard-bath). Sorry.

**Comment by alexreg** [comment]
Thanks for the quick reply, as ever. Is there any easy hack to get around this, even if it's non-compliant?

**Comment by alex-ball** [comment]
Absolutely. The space is removed using the mechanism mentioned in the main biblatex manual:

```tex
 \renewcommand*{\ppspace}{}
```

So all you have to do is put it back again the same way:

```tex
 \renewcommand*{\ppspace}{\addnbspace}
```

**Comment by alexreg** [comment]
Ah, perfect, thank you.
