### ISSUE TITLE
Titles of @inbook entries formatted in quotes rather than italics

### ISSUE THREAD

**Issue by alexreg** [alex-ball/bathbib#13]
I see that titles of @inbook entries are formatted in quotes rather than italics. While I agree this makes sense and accords with the style in most cases, I have certain cases where essays or books are (re)published as chapters/sections within books, and for these I think it makes sense to keep the italic format for the title. What's the best way to go about this?

Thanks in advance.

**Comment by alex-ball** [comment]
Bath's Harvard style doesn't use quotes so presumably you've added those yourself, but I take your point. As you say, the idea is that whole published units like books and journal issues get italic titles while parts within them, like articles and chapters, have upright titles.

Legacy BibTeX isn't subtle enough for the kinds of distinctions you want to make – neither is the Harvard (Bath) specification, come to that – but biblatex does have the ability to make some very granular distinctions:

- `@inbook` is for one self-contained work within a collection all written by the same author;
- `@incollection` is for one self-contained work within a collection where each is written by a different author;
- `@inreference` is for an entry in a dictionary or encyclopedia;
- `@bookinbook` is for a work that was originally published as a standalone item but is now in a collection.

It sounds like you want `@bookinbook`.

You could go even more subtle:

```bibtex
@book{reid1966ptp,
  author = {D. R. Reid},
  year = {1966},
  title = {Physical Testing of Polymer Films},
  related = {reid1967ptp},
  relatedstring = {Reprinted in}}
@book{reid1967ptp,
  pages = {143-183},
  crossref = {pinner1967mpf}}
@book{pinner1967mpf,
  year = {1967},
  editor = {S. H. Pinner},
  title = {Modern Packaging Films},
  address = {London},
  publisher = {Butterworths}}
```

giving you

> Reid, D.R., 1966. *Physical testing of polymer films.* Reprinted in Pinner, S.H., ed. *Modern packaging films.* London: Butterworths, 1967, pp.143–183.

**Comment by alexreg** [comment]
Thanks for the reply. I probably do want `bookinbook`, indeed.

Where are the quotes coming from though? Here's a minimal reproducible example.

```latex
\begin{filecontents*}[overwrite]{\jobname.bib}
@inbook{Hume_1777,
	author = {Hume, David},
	location = {The Strand, London; Edinburgh},
	publisher = {T. Cadell; A. Donaldson \& W. Creech},
	booktitle = {Essays and Treatises on Several Subjects},
	date = {1777},
	langid = {british},
	related = {HTO_EcHU},
	relatedstring = {Published in},
	title = {An Enquiry concerning Human Understanding},
	volume = {II},
}
@book{HTO_EcHU,
	author = {Hume, David},
	editor = {Millican, Peter},
	publisher = {Hume Texts Online},
	url = {https://davidhume.org/texts/e/},
	langid = {british},
	title = {An Enquiry concerning Human Understanding},
	urldate = {2021-09-01},
}
\end{filecontents*}

\documentclass[a4paper, 11pt]{article}

\usepackage[british]{babel}
\usepackage[
	backend = biber,
	giveninits,
	indexing,
	style = bath,
	sorting = ynt,
	uniquename = init,
]{biblatex}

\addbibresource{\jobname.bib}

\begin{document}

    \citetitle{Hume_1777} was written by \citeauthor{Hume_1777}.

    \nocite{*}
    \printbibliography

\end{document}
```

<img width="545" src="https://user-images.githubusercontent.com/67036/134949951-d5a46384-facd-4d40-8b92-2020fcec0159.png">

As you can see, the title there is enclosed in quotes rather than italicised. Presumably it's automatic biblatex behaviour, but does it conform with the Harvard Bath style?

**Comment by alex-ball** [comment]
Oh, I see. I didn't realise you were talking about `\citetitle`, which has its own independent formatting. At the time of writing, this comes from line 455 of `biblatex.def`:

```latex
\DeclareFieldFormat
  [article,inbook,incollection,inproceedings,patent,thesis,unpublished]
  {citetitle}{\mkbibquote{#1\isdot}}
```

You can override this yourself with `\DeclareFieldFormat` if you want. To get the orthographically correct quotes for British English (or whatever `babel` language you have set), you also need `csquotes`:

```latex
\usepackage{csquotes}
```

**Comment by alexreg** [comment]
I see, thank you. What's the "correct" way to do it in this case? Just leave it as quoted? (With the understanding that the chapter was originally an essay, published in another book, rather than a book itself.)

**Comment by alex-ball** [comment]
Yes, for a work that was originally in a collection and is still in a collection, use `@inbook` or `@incollection` as appropriate and leave the `\citetitle` format as quoted.

**Comment by alexreg** [comment]
Thank you.
