### ISSUE TITLE
Correctly place [Online] in CSL version without testing variables?

### ISSUE THREAD

**Issue by alex-ball** [alex-ball/bathbib#16]
At the time of writing, there seem to be differences between CSL implementations as to what happens when a variable is printed:

- `citeproc-js` prevents any variable (apart from dates) being printed twice, but does not delete them, so `<cs:if>` tests for them will still return true. There is no difference in behaviour between variables printed directly or via the `<cs:substitute>` element.
- The Haskell `citeproc` library does not prevent variables being printed twice, but will delete variables printed via the `<cs:substitute>` element, so that subsequent `<cs:if>` tests for them will return false: jgm/citeproc#101

In some circumstances with Harvard (Bath), elements follow the `title` variable when it moves to the head of the reference, such as the ‘\[Online]’ label, at least for audiovisual resources. The challenge is how to avoid having such elements printed in both positions.

Up till now, a variable test has been used; `<cs:substitute>` falls back to `editor` then `title` if `author` is missing, so the title will only move if both the author and editor are missing. But with this difference in implementation, when the `online` macro is processed for the second time, this situation arises with the possible tests:

| Input | Print element? | If variable... | `citeproc-js` | `citeproc` (hs) |
| --- | --- | --- | --- | --- | 
| author, title | Yes | "author editor" "any" | True | True |
|  |  | "title" | True | True |
| editor, title | Yes | "author editor" "any" | True | False |
|  |  | "title" | True | True |
| title | No | "author editor" "any" | False | False |
|  |  | "title" | True | False |

The author/editor test works with `citeproc-js` while the title test does not; the opposite is true for Haskell `citeproc`

Is there a way of suppressing the second `online` macro, when the title has moved, that does not rely on either of these tests?

**Comment by alex-ball** [comment]
@bwiernik I would be grateful for any suggestions. Is your thought that if I could have the same `title` macro in both positions, both implementations would skip it at the natural title position if it had already been processed in `<cs:substitute>`?

**Comment by bwiernik** [comment]
Can you please give some examples of the citations you actually need to produce? I'm not sure there is any actual problem based on what you've described your requirements are

**Comment by bwiernik** [comment]
> Is your thought that if I could have the same title macro in both positions, both implementations would skip it at the natural title position if it had already been processed in <cs:substitute>?

Yes, exactly

**Comment by alex-ball** [comment]
The [specification for the style](https://library.bath.ac.uk/referencing/harvard-bath) is on the University of Bath LibGuides pages (also [as PDF](https://www.bath.ac.uk/library/gen/referencing/harvard-bath-print.pdf)). I have all the references from that page [translated to LaTeX format](https://github.com/alex-ball/bathbib/blob/master/csl/bath-csl-test.tex) in the `csl` directory of this repository, with the corresponding [bibliographic information as YAML](https://github.com/alex-ball/bathbib/blob/master/csl/bath-csl-test.yaml).

This issue came to my attention in particular for the `book` type (where we have the example of an online edited book) and the `motion_picture` type (where the *Elephant man* film is accessed online and cited by title, but we also have YouTube videos such as the Moran reference cited by author).

The difficulty lies in the fact that, for instance, a translated title would come between the title and [Online] in the natural position, but it would stay where it was if title and [Online] moved to the head of the reference.

**Comment by bwiernik** [comment]
There is a lot in those guidelines. Can you please just give me two specific examples?

**Comment by alex-ball** [comment]
I'm sorry, I thought I had. The problem is better illustrated with three examples:

*The elephant man* [Online], 1980. Film. Directed by David Lynch. USA: Brooksfilms. Available from: BBC iPlayer [Accessed 4
 May 2021].

Moran, C., 2016. *Save our libraries* [Online]. Available from: <https://www.youtube.com/watchv=gKTfCz4JtVE&feature=youtu.be> [Accessed 29 April 2016].

Haynes, W.M., ed., 2014. *CRC handbook of chemistry and physics* [Online]. 94th ed. Boca Raton, Fla.: CRC Press/Taylor and Francis. Available from: <http://www.hbcpnetbase.com> [Accessed 16 June 2016].

Thanks for looking into it.

**Comment by bwiernik** [comment]
Okay, yes, like I've described above, that is accomplished by calling a macro under `<substitute>` rather than a variable. Look at apa.csl for an example: https://github.com/citation-style-language/styles/blob/76b4268412474919fd3a300a89d94948680fb941/apa.csl#L371

Something like:

```
<macro name="title-plus-extra"/>
  <group delimiter=" ">
    <text variable="title" font-face="italic"/>
    <choose>
      <if variable="medium">
        <text variable="medium" prefix="[" suffix="]"/>
      </if>
      <else-if variable="URL">
        <text term="online" text-case="capitalize-first" prefix="[" suffix="]"/>
      </else-if>
    </choose>
  </group>
</macro>
<names variable="author">
  <substitute>
    <names variable="editor"/>
    <text macro="title-plus-extra"/>
  </substitute>
</names>
```

**Comment by alex-ball** [comment]
I'm struggling to understand here what is expected behaviour and what is potentially a bug. I have been experimenting with the pandoc (Haskell) implementation and a [minimal working example](https://gist.github.com/alex-ball/9c2bb461488d50c6468033ad5288f0c4) and indeed your code does the job of eliminating the repeated "Online":

```xml
<macro name="title-plus-extra">
  <group delimiter=" ">
    <text variable="title" font-style="italic"/>
    <text variable="genre" prefix="[" suffix="]"/>
    <choose>
      <if variable="URL">
        <text term="online" text-case="capitalize-first" prefix="[" suffix="]"/>
      </if>
    </choose>
  </group>
</macro>
```

But if I split out the "Online" to a macro (because the logic is more complicated than this and it occurs in several other places) it *does not* work and the "Online" is repeated:

```xml
<macro name="title-plus-extra">
  <group delimiter=" ">
    <text variable="title" font-style="italic"/>
    <text variable="genre" prefix="[" suffix="]"/>
    <text macro="online"/>
  </group>
</macro>
<macro name="online">
  <choose>
    <if variable="URL">
      <text term="online" text-case="capitalize-first" prefix="[" suffix="]"/>
    </if>
  </choose>
</macro>
```

That is of course merely inelegant rather than a show-stopping problem. The bigger issue is that (as things stand at the moment) the elements *between* the title and "Online" *do not* move before the date – so in this example the `genre` should stay *after* the date. Up to this point, I have been using different macros for title-as-substitute and title-proper:

```xml
<macro name="author">
  <names variable="author">
    <substitute>
      <names variable="editor">
        <name/>
        <label form="short" prefix=", " text-case="lowercase"/>
      </names>
      <text macro="title-label"/>
    </substitute>
  </names>
</macro>
<macro name="title-label">...</macro>
<macro name="title-plus-extra">...</macro>
```

What I find interesting is that if `title-plus-extra` and `title-label` are identical (to the first `title-plus-extra` above), then "Online" is suppressed as desired but if I then modify `title-label` to remove the unwanted elements, "Online" is again printed in both positions.

So if I have to use the same macro twice, this brings me back to my original problem (but from a different angle): how do I arrange it so that the intermediate elements like `genre` are *not* printed when first encountered in the `<substitute>` block, but *are* printed in the position where `title-plus-extra` occurs the second time, without relying on `<if>`?

**Comment by alex-ball** [comment]
As we are dealing with edge cases that do not have templates in the Harvard (Bath) specification, after some negotiations with my colleagues who maintain it, we have agreed an interpretation such that

- the elements that appear alongside the title in the title block will move with it to the head of the reference (i.e. title transliteration, title translation, software version, bracketed medium/format, `[Online]`)
- as you suggested, the `[Online]` annotation is superseded by a bracketed medium/format if both would appear in the title block.

There are still some formatting differences (e.g. book titles are set upright at the head of the reference but italic otherwise) so that means I have to have two slightly different macros instead of using the same one twice. This makes me uneasy, because I am still not sure about the extent of difference between them that is tolerated before the "online" term gets printed twice, but I have a solution that works with `citeproc-js` and Haskell `citeproc` for the examples I have to work with. I just don't want to be in a position where I have to test against every available implementation.

My solution will still break with `citeproc-js` for cases where someone tries to use the `entry` type without supplying a `container-title` (since the `title` and `container-title` are supposed to swap places) but hopefully no-one will try doing that.
