### ISSUE TITLE
[Help Wanted] Adding Article Numbers

### ISSUE THREAD

**Issue by AnzhiZhang** [alex-ball/bathbib#18]
Hi, I am using the [Leeds Harvard](https://library.leeds.ac.uk/referencing-examples/9/leeds-harvard) referencing style. In Leeds Harvard, [journal article with article number](https://library.leeds.ac.uk/referencing-examples/9/leeds-harvard/11/journal-article#:~:text=Articles%20that%20use%20article%20numbers) required a field `article no: xxx [no pagination]`

Family name, INITIAL(S). Year. Title of article. _Journal Title_. **Volume**, article no: article number [no pagination]

I am using Bath Harvard because it's similar to Leeds Harvard, however, Bath Harvard does not have a field for article numbers. I'd really appreciate it if you could provide any help on how to add this to my reference.

**Comment by alex-ball** [comment]
That's not true, there is support for article numbers (`eid` field) in both `bath-bst` and `biblatex-bath`.

Using BibTEX:

```latex
\begin{filecontents*}[overwrite]{\jobname.bib}
@article{chou.etal2014,
  author = {Chou, C.L. and Teherani, A. and Masters, D.E. and Vener, M. and Wamsley, M. and Poncelet, A.},
  year = {2014},
  title = {Workplace learning through peer groups in medical school clerkships},
  journal = {Medical Education Online},
  volume = {19},
  eid = {article no: 25809 [no pagination]},
}
\end{filecontents*}

\documentclass[margin=3mm,varwidth=80ex]{standalone}

\usepackage{natbib}
\setlength{\bibhang}{0pt}
\newcommand*{\urlprefix}{Available from: }
\newcommand*{\urldateprefix}{Accessed }
\bibliographystyle{bathx}

\begin{document}
\cite{chou.etal2014}
\bibliography{\jobname}
\end{document}
```
![mwe1](https://github.com/alex-ball/bathbib/assets/1890395/435e2325-3cb8-4124-87b2-dd929054a5b6)


Using biblatex:

```latex
\begin{filecontents*}[overwrite]{\jobname.bib}
@article{chou.etal2014,
  author = {Chou, C.L. and Teherani, A. and Masters, D.E. and Vener, M. and Wamsley, M. and Poncelet, A.},
  date = {2014},
  title = {Workplace learning through peer groups in medical school clerkships},
  journaltitle = {Medical Education Online},
  volume = {19},
  eid = {25809},
}
\end{filecontents*}

\documentclass[margin=3mm,varwidth=80ex]{standalone}

\usepackage[british]{babel}
\usepackage{csquotes}
\usepackage[style=bath]{biblatex}
\DeclareFieldFormat[article]{volume}{\textbf{#1}}
\DeclareFieldFormat[article]{eid}{article no:\addspace#1\addspace[no pagination]}
% biblatex-bath loads xpatch
\xpatchbibmacro{journal+issuetitle}{%
  \usebibmacro{isonline}\setunit*{\addcomma\space}%
}{%
  \usebibmacro{isonline}\setunit*{\addperiod\space}%
}{}{}
\addbibresource{\jobname.bib}

\begin{document}
\cite{chou.etal2014}
\printbibliography
\end{document}
```
![mwe2](https://github.com/alex-ball/bathbib/assets/1890395/9d8f7a21-25bd-4cbb-a8bb-e63888f3059a)

**Comment by AnzhiZhang** [comment]
Thanks! I'd like to know that is there any different between `\adddot` and `\addperiod` in patching `journal+issuetitle`?

**Comment by alex-ball** [comment]
Sorry, yes, you are absolutely right, the correct command to use is `\addperiod` (now amended in previous comment). The `\addperiod` command is for full stops between blocks, `\adddot` is for marking abbreviations. The two have different interactions with other punctuation, and may trigger slightly different spacing (unless `\frenchspacing` is active).
