### ISSUE TITLE
British Date Format

### ISSUE THREAD

**Issue by AnzhiZhang** [alex-ball/bathbib#19]
The [Bath Harvard](https://library.bath.ac.uk/referencing/harvard-bath) is using british date format like `26 November 2023`. However, the output of this is using US date format like `November 26 2023`.

Bath Harvard:
![image](https://github.com/alex-ball/bathbib/assets/37402126/b7a0d626-ff0f-4f3f-9ef7-5adaa5be9301)

Actual Output:
![image](https://github.com/alex-ball/bathbib/assets/37402126/14aca8e3-aaff-42a1-93ab-5801bf1897f8)
![image](https://github.com/alex-ball/bathbib/assets/37402126/2280fead-c5b1-4bf2-bce1-7b3e1dd7f9dd)

Expected Output:
![image](https://github.com/alex-ball/bathbib/assets/37402126/373f9a1b-23b9-460a-8a6f-b8244f8d160b)

I am fixing this by add `babel` package:

```latex
\usepackage[british]{babel}
```

**Comment by alex-ball** [comment]
Yes, that's right. The date format comes from the language setting you apply with babel or polyglossia. That is how it is supposed to work.

In other words, this is a feature, not a bug. :-)

The Harvard (Bath) style is written for the University of Bath, which is a UK institution and therefore the assumption is that you are writing in British English, which means you should have

```latex
\usepackage[british]{babel}
```

or the equivalent polyglossia command in your document. Not only does this give you the British date format, it also gives you British hyphenation rules and (if you aren't hard-coding them) quotation mark conventions.

If you really do want to write your document in American English, it is not the job of this bibliography style to get in your way.
