### ISSUE TITLE
Next version of biblatex will probably drop xstring

### ISSUE THREAD

**Issue by moewew** [alex-ball/bathbib#2]
For the upcoming version we are currently planning on getting rid of `xstring` code in `biblatex`. As a consequence `biblatex` would not require `xstring` any more and would not load the `xstring` package itself any more. `biblatex` styles that need `xstring` would have to load the package explicitly themselves. See https://github.com/plk/biblatex/pull/816 for the current state of affairs.

Your style uses some `xstring` commands, for example in

https://github.com/alex-ball/bathbib/blob/68674a2e88d6144d699ad48cdd2f334d76769ecc/biblatex/biblatex-bath.dtx#L2276-L2282

To continue working properly, the files that use those commands should load `xstring`.

Even if it turns out that the change can not go through as planned, it is still a very good idea to load `xstring` explicitly if your style needs it.

We are hoping to release a new version of `biblatex` in the not too distant future (I can't promise any ETA as of now, there will be a pre-release announcement on [comp.text.tex](https://groups.google.com/forum/#!forum/comp.text.tex)). You can learn more about the upcoming changes in https://github.com/plk/biblatex/blob/dev/doc/latex/biblatex/CHANGES.md. If you can find time to test your style against the new dev version (https://sourceforge.net/projects/biblatex/files/development/, you'll also need Biber 2.12 from https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/development/binaries/) feedback would be appreciated.

**Comment by alex-ball** [comment]
Thanks for letting me know. I have released a fix.

**Comment by moewew** [comment]
Thank you for the quick response.

**Comment by moewew** [comment]
Sorry to bother you again. Something seems to have gone awry with the update.

The CTAN page for `biblatex-bath` already shows v2.0.1. But the documentation and code behind that (https://ctan.org/tex-archive/macros/latex/contrib/biblatex-contrib/biblatex-bath) are still v2.0 (I tried several mirrors, all with the same result). The update announcement went to CTAN-ann yesterday: https://lists.dante.de/pipermail/ctan-ann/2018-October/011892.html, which usually means that the update was installed on CTAN the day before.

Incidentally, TeX live only just picked up the package (https://tug.org/pipermail/tex-live-commits/2018-October/007660.html), but that seems to be v2.0 as well.

**Comment by alex-ball** [comment]
Thanks for spotting. I have re-submitted the update, let's hope it works this time.

Regarding TeX Live, I wondered if this release might do the trick. It has been niggling me for some time that they picked up bath-bib but ignored biblatex-bath when I released them both in April; I [contacted the list](https://tug.org/pipermail/tex-live/2018-August/042169.html) to ask if I had done something wrong, but got nowhere. I'm glad the wait is over and I can now update the installation instructions accordingly.

**Comment by moewew** [comment]
There it is: https://tug.org/pipermail/tex-live-commits/2018-October/007667.html Everything seems to have worked this time. Thanks again.
